# apiVersion: v1
# kind: Service

# metadata:
#   name: load-balancer
  
# spec:
#   type: LoadBalancer
#   selector:
#     app: frontend
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: expose-app
spec:
  type: LoadBalancer
  ports:
   - port: 8000
     targetPort: 8000
  selector:
    app: python
    name: iti-app